name: Validate .github
on:
  # TODO: consider if we can trigger this from students' repos everytime they
  # push using a PAT with no access. Then we can run this every 24h. See
  # https://github.com/orgs/community/discussions/26323.
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - run: nix-shell --run './validate.sh'
        env:
          GUARD_GITHUB_TOKEN: ${{ secrets.GUARD_GITHUB_TOKEN }}
